baseUrl = "https://360yun.org/"
languageCode = "zh-CN"
DefaultContentLanguage = "en"
title = "Wayne"
disqusShortname = "k8swayne"
theme = "meghna-hugo"
summaryLength = 30
paginate = 10

# Enable Baidu Analytics by entering your tracking code
googleAnalytics = "c3c51c6790e932d34fd1bf6e0e637537"
hasCJKLanguage = "true"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "产品特点"
    URL = "services"
    weight = 2
	
	[[menu.nav]]
    name = "应用场景"
    URL = "about"
    weight = 3

    [[menu.nav]]
    name = "社区"
    URL = "team-skills"
    weight = 4

    [[menu.nav]]
    name = "用户"
    URL = "portfolio"
    weight = 5

    [[menu.nav]]
    name = "博客"
    URL = "blog"
    weight = 6

    [[menu.nav]]
    name = "联系我们"
    URL = "contact-us"
    weight = 7
	
	[[menu.nav]]
    name = "用户文档"
    URL = "wayne" #"https://360yun.org/wayne/"
    weight = 8
	

# Site params
[params]
home= "首页"
logo = "img/logo.png"


# Meta data
description = "360云平台"
author = "Qihoo"
# Google Analitycs
googleAnalitycsID = "c3c51c6790e932d34fd1bf6e0e637537"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/bg.jpg"
    heading = "WAYNE"
    content= "Wayne 是一个通用的、基于 Web 的 Kubernetes 多集群管理平台。通过可视化 Kubernetes 对象模板编辑的方式，降低业务接入成本，拥有完整的权限管理系统，适应多租户场景，是一款适合企业级集群使用的发布平台。"
    btn = true
    btnText="在线演示"
    btnURL="https://demo.360yun.org/"


    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Github Stars"
        icon = "tf-ion-android-happy"
        count = "2653"

        [[params.counter.counterItem]]
        title = "Committer"
        icon = "tf-ion-archive"
        count = "18"

        [[params.counter.counterItem]]
        title = "Closed Community Issues"
        icon = "tf-ion-thumbsup"
        count = "170"

        [[params.counter.counterItem]]
        title = "Releases"
        icon = "tf-ion-coffee"
        count = "17"

    # footer
    [params.footer]
        copyright = "Qihoo 360"
        copyrightURL = "http://www.themefisher.com"

